---
book_repo: pivotal-cf/docs-book-pcfservices
layout_repo: pivotal-cf/docs-layout-repo
layout_repo_ref: master

feedback_enabled: true

broken_link_exclusions: iefix|arrowhead
repo_link_enabled: true

public_host: docs.pivotal.io

elastic_search: true

sections:
# cross-product resources
- repository:
    name: pivotal-cf/docs-pdfs
  directory: archives
- repository:
    name: pivotal-cf/product-compatibility-matrix
  directory: resources
- repository:
    name: pivotal-cf/docs-pcf-upgrade 
  directory: upgrading
- repository:
    name: pivotal-cf/pcf-release-notes
  directory: releasenotes

# repos in org cloudfoundry
- repository:
    name: cloudfoundry/docs-bbr
  directory: bbr
  subnav_template: bbr-subnav.erb

# repos in org pivotal-cf: alphabetical
- repository:
    name: pivotal-cf/docs-addon-fim
  directory: addon-fim
  subnav_template: addon_fim.erb
- repository:
    name: pivotal-cf-experimental/docs-appdog
  directory: pcf-appdog
  subnav_template: appdog.erb
- repository:
    ref: '1.9'
    name: pivotal-cf/docs-jmx-bridge
  directory: jmx-bridge/1-9
  subnav_template: pivotal_jmx_bridge_1_9_subnav.erb
  product_info:
    use_local_header: true
    latest_stable_version: 1.9
    local_header_img: /images/cloud_rings.png
    local_header_title: JMX Bridge
    search_placeholder: Search JMX Bridge 1.9
    url_prefix: jmx-bridge/1-9
    local_product_version: 1.9
    local_header_links: []
    local_header_version_list:
      - <a href="http://docs.pivotal.io/jmx-bridge/1-8/index.html">v1.8</a>
      - <a href="http://docs.pivotal.io/jmx-bridge/1-7/index.html">v1.7</a>
- repository:
    name: pivotal-cf/docs-jmx-bridge
  directory: jmx-bridge/1-8
  subnav_template: pivotal_jmx_bridge_subnav.erb
  product_info:
    use_local_header: true
    latest_stable_version: 1.9
    local_header_img: /images/cloud_rings.png
    local_header_title: JMX Bridge
    search_placeholder: Search JMX Bridge 1.8
    url_prefix: jmx-bridge/1-8
    local_product_version: 1.8
    local_header_links: []
    local_header_version_list:
      - <a href="http://docs.pivotal.io/jmx-bridge/1-9/index.html">v1.9</a>
      - <a href="http://docs.pivotal.io/jmx-bridge/1-7/index.html">v1.7</a>
- repository:
    name: pivotal-cf/docs-jmx-bridge
    ref: '1.7'
  directory: jmx-bridge/1-7
  subnav_template: pivotal_jmx_bridge_1_7_subnav.erb
  product_info:
    use_local_header: true
    latest_stable_version: 1.9
    local_header_img: /images/cloud_rings.png
    local_header_title: JMX Bridge
    search_placeholder: Search PCF JMX Bridge 1.7
    url_prefix: jmx-bridge/1-7
    local_product_version: 1.7
    local_header_links: []
    local_header_version_list:
      - <a href="http://docs.pivotal.io/jmx-bridge/1-9/index.html">v1.9</a>
      - <a href="http://docs.pivotal.io/jmx-bridge/1-8/index.html">v1.8</a>
- repository:
    name: pivotal-cf/docs-logsearch
  directory: logsearch
  subnav_template: pivotal_logsearch_subnav.erb

- repository:
    name: pivotal-cf/docs-pcf-dev
  directory: pcf-dev
  subnav_template: pivotal_pcfdev_subnav.erb
- repository:
    name: pivotal-cf/docs-phd-ds
  directory: pivotalhd-ds
  subnav_template: pivotal_ds_subnav.erb

- repository:
    name: pivotal-cf/docs-spring-flo
  directory: spring-flo
  subnav_template: spring_flo_subnav.erb
- repository:
    name: pivotal-cf/docs-spring-xd
  directory: spring-xd
  subnav_template: spring_xd_service_subnav.erb

# repos in other orgs: alphabetical by org
- repository:
    name: cfmobile/docs-app-distribution
  directory: app-dist
  subnav_template: app_dist_subnav.erb
- repository:
    name: cfmobile/docs-push-notifications
    ref: '1.9'
  directory: push/1-9
  subnav_template: push_subnav_1-9.erb
  product_info:
    use_local_header: true
    latest_stable_version: 1.9
    changelog_href: http://docs.pivotal.io/push/1-9/release-notes.html
    local_header_img: /images/cloud_rings.png
    local_header_title: Push Notification Services
    search_placeholder: Search PCF Push 1.9
    url_prefix: push/1-9
    local_product_version: 1.9
    local_header_links: []
    local_header_version_list:
      - url_prefix: http://docs.pivotal.io/push/1-8
        display_name: v1.8
      - <a href="http://docs.pivotal.io/archives/push-notifications-1.7.pdf">v1.7</a>
      - <a href="http://docs.pivotal.io/archives/push-notifications-1.6.pdf">v1.6</a>
- repository:
    name: cfmobile/docs-push-notifications
    ref: '1.8'
  directory: push/1-8
  subnav_template: push_subnav_1-8.erb
  product_info:
    use_local_header: true
    latest_stable_version: 1.9
    changelog_href: http://docs.pivotal.io/push/1-8/release-notes.html
    local_header_img: /images/cloud_rings.png
    local_header_title: Push Notification Services
    search_placeholder: Search PCF Push 1.8
    url_prefix: push/1-8
    local_product_version: 1.8
    local_header_links: []
    local_header_version_list:
      - url_prefix: http://docs.pivotal.io/push/1-9
        display_name: v1.9
      - <a href="http://docs.pivotal.io/archives/push-notifications-1.7.pdf">v1.7</a>
      - <a href="http://docs.pivotal.io/archives/push-notifications-1.6.pdf">v1.6</a>

- repository:
    name: gemfire/docs-gemfire-cf
  directory: gemfire-cf
  subnav_template: gemfire_pcf_subnav.erb
- repository:
    name: gemfire/docs-ssc-gemfire-cf
  directory: ssc-gemfire
  subnav_template: gemfire_cf_subnav.erb

- repository:
    name: bentarnoff/docs-tracker-pcf
  directory: tracker-pcf
  subnav_template: pivotal_tracker_subnav.erb

- repository:
    ref: '1.1'
    name: pivotal-cf/docs-scheduler
    at_path: docs-content
  directory: pcf-scheduler/1-1
  subnav_template: pcf-scheduler-1-1_subnav.erb
  product_info:
    use_local_header: true
    latest_stable_version: 1.1
    local_header_img: /images/cloud_rings.png
    local_header_title: Scheduler for PCF
    search_placeholder: Search Scheduler for PCF 1.1
    url_prefix: pcf-scheduler/1-1
    local_product_version: 1.1
    local_header_links: []
    local_header_version_list:
      - url_prefix: http://docs.pivotal.io/pcf-scheduler/1-0
        display_name: v1.0
- repository:
    ref: 'master'
    name: pivotal-cf/docs-scheduler
    at_path: docs-content
  directory: pcf-scheduler/1-0
  subnav_template: pcf-scheduler-subnav.erb
  product_info:
    use_local_header: true
    latest_stable_version: 1.1
    local_header_img: /images/cloud_rings.png
    local_header_title: Scheduler for PCF
    search_placeholder: Search Scheduler for PCF 1.0
    url_prefix: pcf-scheduler/1-0
    local_product_version: 1.0
    local_header_links: []
    local_header_version_list:
      - url_prefix: http://docs.pivotal.io/pcf-scheduler/1-1
        display_name: v1.1
      
