---
book_repo: pivotal-cf/docs-book-pcfservices
layout_repo: pivotal-cf/docs-layout-repo

broken_link_exclusions: iefix|arrowhead
repo_link_enabled: true

public_host: docs.pivotal.io

elastic_search: true

sections:
# cross-product resources
- repository:
    name: pivotal-cf/docs-pdfs
  directory: archives
- repository:
    name: pivotal-cf/product-compatibility-matrix
  directory: resources

# repos in org pivotal-cf: alphabetical
- repository:
    name: pivotal-cf/docs-addon-ipsec
  directory: addon-ipsec
  subnav_template: addon_ipsec.erb
- repository:
    name: pivotal-cf/docs-apigee
  directory: apigee
  subnav_template: apigee_subnav.erb
- repository:
    name: pivotal-cf/docs-appdynamics
  directory: appdynamics
  subnav_template: _appdynamics_subnav.erb
- repository:
    name: pivotal-cf/docs-appmon
  directory: appmon
  subnav_template: pivotal_dynatrace_service_subnav.erb
- repository:
    name: pivotal-cf/docs-aws-services
  directory: aws-services
  subnav_template: aws_services_subnav.erb
- repository:
    name: pivotal-cf/docs-cassandra
  directory: cassandra
  subnav_template: pivotal_cassandra_service_subnav.erb
- repository:
    name: pivotal-cf/docs-cloudbees
  directory: cloudbees
  subnav_template: pivotal_cloudbees_service_subnav.erb
- repository:
    name: pivotal-cf/docs-cloudbees-cjoc
  directory: cjoc
  subnav_template: cjoc_subnav.erb
- repository:
    name: pivotal-cf/docs-cloudsoft
  directory: cloudsoft
  subnav_template: cloudsoft_subnav.erb
- repository:
    name: pivotal-cf/docs-edb-postgres
  directory: edb-postgres
  subnav_template: pivotal_edb_postgres.erb
- repository:
    name: pivotal-cf/docs-gitlab
  directory: gitlab
  subnav_template: pivotal_gitlab_service_subnav.erb
- repository:
    name: pivotal-cf/docs-identity
  directory: p-identity
  subnav_template: pivotal_sso_subnav.erb
- repository:
    name: pivotal-cf/docs-jfrog
  directory: jfrog
  subnav_template: pivotal_jfrog_service_subnav.erb
- repository:
    name: pivotal-cf/docs-jmx-bridge
  directory: jmx-bridge
  subnav_template: pivotal_jmx_bridge_subnav.erb 
- repository:
    name: pivotal-cf/docs-klacloud
  directory: knowtify
  subnav_template: pivotal_knowtify_service_subnav.erb
- repository:
    name: pivotal-cf/docs-logsearch
  directory: logsearch
  subnav_template: pivotal_logsearch_subnav.erb
- repository:
    name: pivotal-cf/docs-metrics
  directory: pcf-metrics
  subnav_template: pcf_metrics_subnav.erb
- repository:
    name: pivotal-cf/docs-metrics
    ref: edge
  directory: pcf-metrics-edge
  subnav_template: pcf_metrics_edge_subnav.erb
- repository:
    name: pivotal-cf/docs-mongodb
  directory: mongodb
  subnav_template: pivotal_mongodb_service_subnav.erb
- repository:
    name: pivotal-cf/docs-mongodb-managed
  directory: mongodb-managed
  subnav_template: pivotal_mongodb_managed_subnav.erb
- repository:
    name: pivotal-cf/docs-mysql
  directory: p-mysql
  subnav_template: pivotal_mysql_service_subnav.erb
- repository:
    name: pivotal-cf/docs-mysql
    ref: 1.8.0
  directory: edge/p-mysql
  subnav_template: pivotal_edge_mysql_service_subnav.erb
- repository:
    name: pivotal-cf/docs-neo4j
  directory: neo4j
  subnav_template: pivotal_neo4j_service_subnav.erb
- repository:
    name: pivotal-cf/docs-new-relic
  directory: newrelic
  subnav_template: pivotal_new_relic_service_subnav.erb
- repository:
    name: pivotal-cf/docs-on-demand-service-broker
    ref: v0.5.x
  directory: on-demand-service-broker
  subnav_template: pivotal_on_demand_broker_subnav_v0-5-0.erb
- repository:
    name: pivotal-cf/docs-partners
  directory: partners
  subnav_template: partners_subnav.erb
- repository:
    name: pivotal-cf/docs-pcf-dev
  directory: pcf-dev
  subnav_template: pivotal_pcfdev_subnav.erb
- repository:
    name: pivotal-cf/docs-phd-ds
  directory: pivotalhd-ds
  subnav_template: pivotal_ds_subnav.erb
- repository:
    name: pivotal-cf/docs-rabbitmq-staging
  directory: rabbitmq-cf
  subnav_template: pivotal_rabbitmq_service_subnav.erb
- repository:
    name: pivotal-cf/docs-redis
  directory: redis
  subnav_template: pivotal_redis_service_subnav.erb
- repository:
    name: pivotal-cf/docs-riakcs
  directory: p-riakcs
  subnav_template: pivotal_riakcs_service.erb
- repository:
    name: pivotal-cf/docs-rlec
  directory: rlec
  subnav_template: pivotal_rlec.erb
- repository:
    name: pivotal-cf/docs-ruxit
  directory: ruxit
  subnav_template: pivotal_ruxit.erb
- repository:
    name: pivotal-cf/docs-service-backup
  directory: service-backup
  subnav_template: pivotal_service_backups_subnav.erb
- repository:
    name: pivotal-cf/docs-service-metrics
  directory: service-metrics
  subnav_template: pivotal_service_metrics_subnav.erb
- repository:
    name: pivotal-cf/docs-solace-messaging
  directory: solace-messaging
  subnav_template: pivotal_solace_messaging.erb
- repository:
    name: pivotal-cf/docs-spring-cloud-data-flow
  directory: spring-cloud-data-flow
  subnav_template: spring_cloud_data_flow_subnav.erb
- repository:
    name: pivotal-cf/docs-spring-cloud-services
  directory: spring-cloud-services
  subnav_template: spring_cloud_subnav.erb
- repository:
    name: pivotal-cf/docs-spring-flo
  directory: spring-flo
  subnav_template: spring_flo_subnav.erb
- repository:
    name: pivotal-cf/docs-spring-xd
  directory: spring-xd
  subnav_template: spring_xd_service_subnav.erb

# repos in other orgs: alphabetical by org
- repository:
    name: cfmobile/docs-app-distribution
  directory: app-dist
  subnav_template: app_dist_subnav.erb
- repository:
    name: cfmobile/docs-push-notifications
  directory: push
  subnav_template: push_subnav.erb

- repository:
    name: dingotiles/dingo-docs
    at_path: docs-dingo-postgresql
  directory: dingo-postgresql
  subnav_template: _dingo_postgresql_subnav.erb

- repository:
    name: gemfire/docs-gemfire-cf
  directory: gemfire-cf
  subnav_template: gemfire_pcf_subnav.erb
- repository:
    name: gemfire/docs-ssc-gemfire-cf
  directory: ssc-gemfire
  subnav_template: gemfire_cf_subnav.erb

- repository:
    name: pivotaltracker/docs-tracker-pcf
  directory: tracker-pcf
  subnav_template: pivotal_tracker_subnav.erb
  
