---
book_repo: pivotal-cf/docs-book-pcfservices
layout_repo: pivotal-cf/docs-layout-repo

feedback_enabled: true

broken_link_exclusions: iefix|arrowhead
repo_link_enabled: true

public_host: docs.pivotal.io

elastic_search: true

- repository:
    ref: '1.9'
    name: pivotal-cf/docs-jmx-bridge
  directory: jmx-bridge/1-9
  subnav_template: pivotal_jmx_bridge_subnav.erb
  product_info:
    use_local_header: true
    latest_stable_version: 1.9
    local_header_img: /images/cloud_rings.png
    local_header_title: JMX Bridge
    search_placeholder: Search JMX Bridge 1.9
    url_prefix: jmx-bridge/1-9
    local_product_version: 1.9
    local_header_links: []
    local_header_version_list:
      - url_prefix: http://docs.pivotal.io/jmx-bridge/1-8
        display_name: v1.8
      - url_prefix: http://docs.pivotal.io/jmx-bridge/1-7
        display_name: v1.7
