---
book_repo: pivotal-cf/docs-book-pcfservices
layout_repo: pivotal-cf/docs-layout-repo

feedback_enabled: true

broken_link_exclusions: iefix|arrowhead
repo_link_enabled: true

public_host: docs.pivotal.io

elastic_search: true

products:
  - id: sso-1-7
    subnav_root: p-identity/1-7/sso-subnav-root.html
  - id: sso-1-8
    subnav_root: p-identity/1-8/sso-subnav-root.html
  - id: sso-1-9
    subnav_root: p-identity/1-9/sso-subnav-root.html
  - id: concourse
    subnav_root: p-concourse/subnav_root.html

pcf_header: &local_pcf
  use_local_header: true
  latest_stable_version: 1.9
  changelog_href: http://docs.pivotal.io/pivotalcf/pcf-release-notes/
  local_header_img: /images/cloud_rings.png
  local_header_title: Pivotal Cloud Foundry
  search_placeholder: Search PCF 1.9
  local_product_version: 1.9
  url_prefix: pivotalcf/1-9
  local_header_links:
    - <a href="https://network.pivotal.io/">Download</a>
    - <a href="https://support.pivotal.io/hc/en-us/requests/new">Ask for Help</a>
    - <a href="https://discuss.pivotal.io/hc/en-us/categories/200072648-Pivotal-CF-Knowledge-Base">PCF Knowledge Base</a>
    - <a href="/archives/pcf-docs-1.9.pdf">PDF</a>
  local_header_version_list:
    - url_prefix: http://docs.pivotal.io/pivotalcf/1-8
      display_name: v1.8
    - url_prefix: http://docs.pivotal.io/pivotalcf/1-7
      display_name: v1.7
    - url_prefix: http://docs.pivotal.io/pivotalcf/1-6
      display_name: v1.6
    - <a href="/archives/pcf-docs-1.5.pdf">v1.5</a>
    - <a href="/archives/pcf-docs-1.4.pdf">v1.4</a>
    - <a href="/archives/pcf-docs-1.3.pdf">v1.3</a>
    - <a href="/archives/pcf-docs-1.2.pdf">v1.2</a>

sections:
# cross-product resources
- repository:
    name: pivotal-cf/docs-pdfs
  directory: archives
- repository:
    name: pivotal-cf/product-compatibility-matrix
  directory: resources
- repository:
    name: pivotal-cf/docs-pcf-upgrade 
  directory: upgrading
  product_info: *local_pcf

# repos in org pivotal-cf: alphabetical
- repository:
    name: pivotal-cf/docs-addon-antivirus
  directory: addon-antivirus
  subnav_template: addon_antivirus.erb
- repository:
    name: pivotal-cf/docs-addon-fim
  directory: addon-fim
  subnav_template: addon_fim.erb
- repository:
    name: pivotal-cf/docs-addon-ipsec
  directory: addon-ipsec
  subnav_template: addon_ipsec.erb
- repository:
    name: pivotal-cf-experimental/docs-appdog
  directory: pcf-appdog
  subnav_template: appdog.erb
- repository:
    name: pivotal-cf/docs-concourse
  directory: p-concourse
  product_id: concourse
- repository:
    name: pivotal-cf/docs-identity
    ref: '1.9'
  directory: p-identity/1-9
  product_id: sso-1-9
  product_info:
    use_local_header: true
    latest_stable_version: 1.9
    local_header_img: /images/cloud_rings.png
    local_header_title: Single Sign-On
    search_placeholder: Search Single Sign-On 1.9
    url_prefix: p-identity/1-9
    local_product_version: 1.9
    local_header_links: []
    local_header_version_list:
      - url_prefix: http://docs.pivotal.io/p-identity/1-8
        display_name: v1.8
      - url_prefix: http://docs.pivotal.io/p-identity/1-7
        display_name: v1.7
- repository:
    name: pivotal-cf/docs-identity
    ref: '1.8'
  directory: p-identity/1-8
  product_id: sso-1-8
  product_info:
    use_local_header: true
    latest_stable_version: 1.9
    local_header_img: /images/cloud_rings.png
    local_header_title: Single Sign-On
    search_placeholder: Search Single Sign-On 1.8
    url_prefix: p-identity/1-8
    local_product_version: 1.8
    local_header_links: []
    local_header_version_list:
      - url_prefix: http://docs.pivotal.io/p-identity/1-9
        display_name: v1.9
      - url_prefix: http://docs.pivotal.io/p-identity/1-7
        display_name: v1.7
- repository:
    name: pivotal-cf/docs-identity
    ref: "1.7"
  directory: p-identity/1-7
  product_id: sso-1-7
  product_info:
    use_local_header: true
    latest_stable_version: 1.9
    local_header_img: /images/cloud_rings.png
    local_header_title: Single Sign-On
    search_placeholder: Search Single Sign-On 1.7
    url_prefix: p-identity/1-7
    local_product_version: 1.7
    local_header_links: []
    local_header_version_list:
      - url_prefix: http://docs.pivotal.io/p-identity/1-9
        display_name: v1.9
      - url_prefix: http://docs.pivotal.io/p-identity/1-8
        display_name: v1.8
- repository:
    name: pivotal-cf/docs-jmx-bridge
  directory: jmx-bridge/1-8
  subnav_template: pivotal_jmx_bridge_subnav.erb
  product_info:
    use_local_header: true
    latest_stable_version: 1.8
    local_header_img: /images/cloud_rings.png
    local_header_title: JMX Bridge
    search_placeholder: Search JMX Bridge 1.8
    url_prefix: jmx-bridge/1-8
    local_product_version: 1.8
    local_header_links: []
    local_header_version_list:
      - url_prefix: http://docs.pivotal.io/jmx-bridge/1-7
        display_name: v1.7
- repository:
    name: pivotal-cf/docs-jmx-bridge
    ref: '1.7'
  directory: jmx-bridge/1-7
  subnav_template: pivotal_jmx_bridge_1_7_subnav.erb
  product_info:
    use_local_header: true
    latest_stable_version: 1.8
    local_header_img: /images/cloud_rings.png
    local_header_title: JMX Bridge
    search_placeholder: Search PCF JMX Bridge 1.7
    url_prefix: jmx-bridge/1-7
    local_product_version: 1.7
    local_header_links: []
    local_header_version_list:
      - url_prefix: http://docs.pivotal.io/jmx-bridge/1-8
        display_name: v1.8
- repository:
    name: pivotal-cf/docs-logsearch
  directory: logsearch
  subnav_template: pivotal_logsearch_subnav.erb

- repository:
    name: pivotal-cf/docs-metrics
    ref: '1.3'
  directory: pcf-metrics/1-3
  subnav_template: pcf_metrics_1_3_subnav.erb
  product_info:
    use_local_header: true
    latest_stable_version: 1.3
    local_header_img: /images/cloud_rings.png
    local_header_title: PCF Metrics
    search_placeholder: Search PCF Metrics 1.3
    url_prefix: pcf-metrics/1-3
    local_product_version: 1.3
    local_header_links: []
    local_header_version_list:
      - url_prefix: http://docs.pivotal.io/pcf-metrics/1-2
        display_name: v1.2
      - url_prefix: http://docs.pivotal.io/pcf-metrics/1-1
        display_name: v1.1
      - url_prefix: http://docs.pivotal.io/pcf-metrics/1-0
        display_name: v1.0
- repository:
    name: pivotal-cf/docs-metrics
    ref: '1.2'
  directory: pcf-metrics/1-2
  subnav_template: pcf_metrics_1_2_subnav.erb
  product_info:
    use_local_header: true
    latest_stable_version: 1.3
    local_header_img: /images/cloud_rings.png
    local_header_title: PCF Metrics
    search_placeholder: Search PCF Metrics 1.2
    url_prefix: pcf-metrics/1-2
    local_product_version: 1.2
    local_header_links: []
    local_header_version_list:
      - url_prefix: http://docs.pivotal.io/pcf-metrics/1-3
        display_name: v1.3
      - url_prefix: http://docs.pivotal.io/pcf-metrics/1-1
        display_name: v1.1
      - url_prefix: http://docs.pivotal.io/pcf-metrics/1-0
        display_name: v1.0
- repository:
    name: pivotal-cf/docs-metrics
    ref: '1.1'
  directory: pcf-metrics/1-1
  subnav_template: pcf_metrics_1_1_subnav.erb
  product_info:
    use_local_header: true
    latest_stable_version: 1.2
    local_header_img: /images/cloud_rings.png
    local_header_title: PCF Metrics
    search_placeholder: Search PCF Metrics 1.1
    url_prefix: pcf-metrics/1-1
    local_product_version: 1.1
    local_header_links: []
    local_header_version_list:
      - url_prefix: http://docs.pivotal.io/pcf-metrics/1-3
        display_name: v1.3
      - url_prefix: http://docs.pivotal.io/pcf-metrics/1-2
        display_name: v1.2
      - url_prefix: http://docs.pivotal.io/pcf-metrics/1-0
        display_name: v1.0
- repository:
    name: pivotal-cf/docs-metrics
    ref: '1.0'
  directory: pcf-metrics/1-0
  subnav_template: pcf_metrics_1_0_subnav.erb
  product_info:
    use_local_header: true
    latest_stable_version: 1.2
    local_header_img: /images/cloud_rings.png
    local_header_title: PCF Metrics
    search_placeholder: Search PCF Metrics 1.0
    url_prefix: pcf-metrics/1-0
    local_product_version: 1.0
    local_header_links: []
    local_header_version_list:
      - url_prefix: http://docs.pivotal.io/pcf-metrics/1-3
        display_name: v1.3
      - url_prefix: http://docs.pivotal.io/pcf-metrics/1-2
        display_name: v1.2
      - url_prefix: http://docs.pivotal.io/pcf-metrics/1-1
        display_name: v1.1

- repository:
    name: pivotal-cf/docs-mysql
    ref: 1.9.0
  directory: p-mysql/1-9
  subnav_template: mysql_subnav_1_9.erb
  product_info:
    use_local_header: true
    latest_stable_version: 1.8
    changelog_href: http://docs.pivotal.io/p-mysql/1-9/release-notes.html
    local_header_img: /images/cloud_rings.png
    local_header_title: MySQL for PCF
    search_placeholder: Search MySQL for PCF 1.9
    url_prefix: p-mysql/1-9
    local_product_version: 1.9
    local_header_links: []
    local_header_version_list:
      - url_prefix: http://docs.pivotal.io/p-mysql/1-8
        display_name: v1.8
      - url_prefix: http://docs.pivotal.io/p-mysql/1-7
        display_name: v1.7
      - <a href="http://docs.pivotal.io/archives/mysql-docs-1.6.pdf">v1.6</a>
      - <a href="http://docs.pivotal.io/archives/mysql-docs-1.5.pdf">v1.5</a>
      - <a href="http://docs.pivotal.io/archives/mysql-docs-1.4.pdf">v1.4</a>
- repository:
    name: pivotal-cf/docs-mysql
    ref: 1.8.0
  directory: p-mysql/1-8
  subnav_template: mysql_subnav_1_8.erb
  product_info:
    use_local_header: true
    latest_stable_version: 1.8
    changelog_href: http://docs.pivotal.io/p-mysql/1-8/release-notes.html
    local_header_img: /images/cloud_rings.png
    local_header_title: MySQL for PCF
    search_placeholder: Search MySQL for PCF 1.8
    url_prefix: p-mysql/1-8
    local_product_version: 1.8
    local_header_links: []
    local_header_version_list:
      - url_prefix: http://docs.pivotal.io/p-mysql/1-9
        display_name: v1.9
      - url_prefix: http://docs.pivotal.io/p-mysql/1-7
        display_name: v1.7
      - <a href="http://docs.pivotal.io/archives/mysql-docs-1.6.pdf">v1.6</a>
      - <a href="http://docs.pivotal.io/archives/mysql-docs-1.5.pdf">v1.5</a>
      - <a href="http://docs.pivotal.io/archives/mysql-docs-1.4.pdf">v1.4</a>
- repository:
    name: pivotal-cf/docs-mysql
    ref: '1.7'
  directory: p-mysql/1-7
  subnav_template: mysql_subnav_1_7.erb
  product_info:
    use_local_header: true
    latest_stable_version: 1.8
    changelog_href: http://docs.pivotal.io/p-mysql/1-7/release-notes.html
    local_header_img: /images/cloud_rings.png
    local_header_title: MySQL for PCF
    search_placeholder: Search MySQL for PCF 1.7
    url_prefix: p-mysql/1-7
    local_product_version: 1.7
    local_header_links: []
    local_header_version_list:
      - url_prefix: http://docs.pivotal.io/p-mysql/1-9
        display_name: v1.9
      - url_prefix: http://docs.pivotal.io/p-mysql/1-8
        display_name: v1.8
      - <a href="http://docs.pivotal.io/archives/mysql-docs-1.6.pdf">v1.6</a>
      - <a href="http://docs.pivotal.io/archives/mysql-docs-1.5.pdf">v1.5</a>
      - <a href="http://docs.pivotal.io/archives/mysql-docs-1.4.pdf">v1.4</a>

- repository:
    name: pivotal-cf/docs-pcf-dev
  directory: pcf-dev
  subnav_template: pivotal_pcfdev_subnav.erb
- repository:
    name: pivotal-cf/docs-phd-ds
  directory: pivotalhd-ds
  subnav_template: pivotal_ds_subnav.erb

- repository:
    name: pivotal-cf/docs-redis
    ref: '1.7'
  directory: redis/1-7
  subnav_template: pivotal_redis_service_subnav-1-7.erb
  product_info:
    use_local_header: true
    latest_stable_version: 1.7
    local_header_img: /images/cloud_rings.png
    local_header_title: Pivotal Redis
    search_placeholder: Search Redis 1.7
    url_prefix: redis/1-7
    local_product_version: 1.7
    local_header_links: []
    local_header_version_list:
      - url_prefix: http://docs.pivotal.io/redis/1-6
        display_name: v1.6
      - url_prefix: http://docs.pivotal.io/redis/1-5
        display_name: v1.5
      - url_prefix: http://docs.pivotal.io/redis/1-4
        display_name: v1.4

- repository:
    name: pivotal-cf/docs-redis
    ref: '1.6'
  directory: redis/1-6
  subnav_template: pivotal_redis_service_subnav-1-6.erb
  product_info:
    use_local_header: true
    latest_stable_version: 1.7
    local_header_img: /images/cloud_rings.png
    local_header_title: Pivotal Redis
    search_placeholder: Search Redis 1.6
    url_prefix: redis/1-6
    local_product_version: 1.6
    local_header_links: []
    local_header_version_list:
      - url_prefix: http://docs.pivotal.io/redis/1-7
        display_name: v1.7
      - url_prefix: http://docs.pivotal.io/redis/1-5
        display_name: v1.5
      - url_prefix: http://docs.pivotal.io/redis/1-4
        display_name: v1.4
- repository:
    name: pivotal-cf/docs-redis
    ref: '1.5'
  directory: redis/1-5
  subnav_template: pivotal_redis_service_subnav-1-5.erb
  product_info:
    use_local_header: true
    latest_stable_version: 1.7
    local_header_img: /images/cloud_rings.png
    local_header_title: Pivotal Redis
    search_placeholder: Search Redis 1.5
    url_prefix: redis/1-5
    local_product_version: 1.5
    local_header_links: []
    local_header_version_list:
      - url_prefix: http://docs.pivotal.io/redis/1-7
        display_name: v1.7
      - url_prefix: http://docs.pivotal.io/redis/1-6
        display_name: v1.6
      - url_prefix: http://docs.pivotal.io/redis/1-4
        display_name: v1.4
- repository:
    name: pivotal-cf/docs-redis
    ref: '1.4'
  directory: redis/1-4
  subnav_template: pivotal_redis_service_subnav-1-4.erb
  product_info:
    use_local_header: true
    latest_stable_version: 1.7
    local_header_img: /images/cloud_rings.png
    local_header_title: Pivotal Redis
    search_placeholder: Search Redis 1.4
    url_prefix: redis/1-4
    local_product_version: 1.4
    local_header_links: []
    local_header_version_list:
      - url_prefix: http://docs.pivotal.io/redis/1-7
        display_name: v1.7
      - url_prefix: http://docs.pivotal.io/redis/1-6
        display_name: v1.6
      - url_prefix: http://docs.pivotal.io/redis/1-5
        display_name: v1.5

- repository:
    name: pivotal-cf/docs-spring-cloud-data-flow
  directory: spring-cloud-data-flow
  subnav_template: spring_cloud_data_flow_subnav.erb

- repository:
    name: pivotal-cf/docs-spring-flo
  directory: spring-flo
  subnav_template: spring_flo_subnav.erb
- repository:
    name: pivotal-cf/docs-spring-xd
  directory: spring-xd
  subnav_template: spring_xd_service_subnav.erb

# repos in other orgs: alphabetical by org
- repository:
    name: cfmobile/docs-app-distribution
  directory: app-dist
  subnav_template: app_dist_subnav.erb
- repository:
    name: cfmobile/docs-push-notifications
    ref: '1.8'
  directory: push/1-8
  subnav_template: push_subnav_1-8.erb
  product_info:
    use_local_header: true
    latest_stable_version: 1.8
    changelog_href: http://docs.pivotal.io/push/1-8/release-notes.html
    local_header_img: /images/cloud_rings.png
    local_header_title: Push Notification Services
    search_placeholder: Search PCF Push 1.8
    url_prefix: push/1-8
    local_product_version: 1.8
    local_header_links: []
    local_header_version_list:
      - url_prefix: http://docs.pivotal.io/push/1-6
        display_name: v1.6
      - url_prefix: http://docs.pivotal.io/push/1-7
        display_name: v1.7
- repository:
    name: cfmobile/docs-push-notifications
    ref: '1.7'
  directory: push/1-7
  subnav_template: push_subnav_1-7.erb
  product_info:
    use_local_header: true
    latest_stable_version: 1.8
    changelog_href: http://docs.pivotal.io/push/1-7/release-notes.html
    local_header_img: /images/cloud_rings.png
    local_header_title: Push Notification Services
    search_placeholder: Search PCF Push 1.7
    url_prefix: push/1-7
    local_product_version: 1.7
    local_header_links: []
    local_header_version_list:
      - url_prefix: http://docs.pivotal.io/push/1-6
        display_name: v1.6
      - url_prefix: http://docs.pivotal.io/push/1-8
        display_name: v1.8
- repository:
    name: cfmobile/docs-push-notifications
    ref: '1.6'
  directory: push/1-6
  subnav_template: push_subnav_1-6.erb
  product_info:
    use_local_header: true
    latest_stable_version: 1.8
    changelog_href: http://docs.pivotal.io/push/1-6/release-notes.html
    local_header_img: /images/cloud_rings.png
    local_header_title: Push Notification Services
    search_placeholder: Search PCF Push 1.6
    url_prefix: push/1-6
    local_product_version: 1.6
    local_header_links: []
    local_header_version_list:
      - url_prefix: http://docs.pivotal.io/push/1-7
        display_name: v1.7
      - url_prefix: http://docs.pivotal.io/push/1-8
        display_name: v1.8

- repository:
    name: gemfire/docs-gemfire-cf
  directory: gemfire-cf
  subnav_template: gemfire_pcf_subnav.erb
- repository:
    name: gemfire/docs-ssc-gemfire-cf
  directory: ssc-gemfire
  subnav_template: gemfire_cf_subnav.erb

- repository:
    name: bentarnoff/docs-tracker-pcf
  directory: tracker-pcf
  subnav_template: pivotal_tracker_subnav.erb

- repository:
    name: pivotal-cf/docs-aws-services
  directory: aws-services
  subnav_template: aws_services_subnav.erb

- repository:
    name: pivotal-cf/docs-book-tiledev
    at_path: docs-content
  directory: tiledev
  subnav_template: tiledev_subnav.erb
